(()=>{
  const PAGE_SIZE=30;
  let visibleCount=PAGE_SIZE,cachedEditions=[],archiveDates=[],publication=null;
  const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
  const isEn=()=>document.body.classList.contains("en");
  function label(n){if(!n)return"";return isEn()?(n===1?"Launch Issue":`Issue #${n}`):(n===1?"창간호":`제${n}호`)}
  function issueNo(date){const asc=[...archiveDates].sort();const i=asc.indexOf(date);return i>=0?i+1:null}
  function kstParts(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),o=Object.fromEntries(p.map(x=>[x.type,x.value]));return{year:+o.year,month:+o.month,day:+o.day}}
  function exactDate(t,y){const m=String(t||"").trim().match(/^(\d{1,2})\/(\d{1,2})$/);return m?{year:y,month:+m[1],day:+m[2]}:null}
  function monthOnly(t){const m=String(t||"").trim().match(/^(\d{1,2})월/);return m?+m[1]:null}
  function cmp(a,b){return a.year-b.year||a.month-b.month||a.day-b.day}
  function filterCalendar(){if(typeof CONFIG==="undefined"||!Array.isArray(CONFIG.calendar))return;const n=kstParts(),cur={year:n.year,month:n.month,day:n.day};if(!window.__TEAM8_ORIGINAL_CALENDAR__)window.__TEAM8_ORIGINAL_CALENDAR__=CONFIG.calendar.map(x=>({...x}));CONFIG.calendar=window.__TEAM8_ORIGINAL_CALENDAR__.filter(c=>{const d=exactDate(c.date,n.year);if(d)return cmp(d,cur)>=0;const m=monthOnly(c.date);return m?m>=n.month:true}).map(c=>{const d=exactDate(c.date,n.year),today=!!d&&d.month===n.month&&d.day===n.day;return{...c,isToday:today,label_kr:today?"오늘":(c.label_kr==="오늘"?"":c.label_kr),label_en:today?"Today":(c.label_en==="Today"?"":c.label_en)}});if(typeof renderCalendar==="function")renderCalendar()}
  function style(){if(document.getElementById("edition-archive-style"))return;const s=document.createElement("style");s.id="edition-archive-style";s.textContent=`.edition-current{font-size:10px;color:var(--muted);margin-top:7px;font-weight:700}.edition-status{display:inline-block;margin-left:7px;padding:2px 6px;border-radius:5px;background:var(--accent-tint);color:var(--accent);font-size:8.5px}.past-briefs{border-top:1px solid var(--line);margin-top:34px;padding:25px 0 6px}.past-head{display:flex;justify-content:space-between;align-items:end;gap:12px;margin-bottom:13px}.past-kicker{font-size:10px;color:var(--accent);font-weight:800;letter-spacing:.08em}.past-title{font-size:18px;font-weight:850;margin-top:3px}.past-sub{font-size:10px;color:var(--muted)}.past-list{display:grid;gap:10px}.past-card{display:grid;grid-template-columns:92px 1fr auto;gap:14px;align-items:center;background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:14px 16px;box-shadow:var(--shadow)}.past-date{font:750 11px var(--mono);color:var(--muted)}.past-issue{font-size:13px;font-weight:850;margin-top:3px}.past-summary{font-size:11px;color:var(--muted);margin-top:4px;line-height:1.5}.past-open{font-size:11px;font-weight:800;color:var(--accent)}.archive-more-wrap{text-align:center;margin-top:14px}.archive-more{border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:9px;padding:9px 18px;font:750 11px var(--font);cursor:pointer}@media(max-width:700px){.past-card{grid-template-columns:76px 1fr}.past-open{grid-column:2}}`;document.head.appendChild(s)}
  async function idx(){const r=await fetch("/api/archive",{cache:"no-store"});if(!r.ok)return[];const j=await r.json();return Array.isArray(j.dates)?j.dates:[]}
  async function pub(){try{const r=await fetch("/api/publication",{cache:"no-store"});return r.ok?await r.json():null}catch{return null}}
  async function ed(d){try{const r=await fetch(`/api/archive?date=${encodeURIComponent(d)}`,{cache:"no-store"});return r.ok?await r.json():null}catch{return null}}
  function summary(x){const d=x?.data?.ai?.insight;return isEn()?(d?.headline?.en||d?.headline?.kr||""):(d?.headline?.kr||d?.headline?.en||"")}
  function sec(){let s=document.getElementById("past-briefs");if(s)return s;s=document.createElement("section");s.id="past-briefs";s.className="past-briefs";(document.querySelector(".main-col")||document.body).appendChild(s);return s}
  function renderCurrent(){const hero=document.querySelector(".hero-card");if(!hero||!publication)return;let m=document.getElementById("edition-current");if(!m){m=document.createElement("div");m.id="edition-current";m.className="edition-current";hero.appendChild(m)}m.innerHTML=isEn()?`${esc(publication.issueDateKST)} · ${esc(label(publication.issueNumber))} · KST 08:00 <span class="edition-status">PUBLISHED</span>`:`${esc(publication.issueDateKST)} · ${esc(label(publication.issueNumber))} · KST 08:00 <span class="edition-status">발행완료</span>`}
  function renderArchive(){const s=sec(),shown=cachedEditions.slice(0,visibleCount),more=visibleCount<cachedEditions.length;s.innerHTML=`<div class="past-head"><div><div class="past-kicker">${isEn()?"ARCHIVE":"지난 브리프"}</div><div class="past-title">${isEn()?"Previous Daily Briefs":"지난 브리프"}</div></div><div class="past-sub">${isEn()?"Latest 30 · 1-year retention · weekdays only":"최근 30호 · 1년 보관 · 평일 발행"}</div></div><div class="past-list">${shown.map(x=>{const n=issueNo(x.date);return`<a class="past-card" href="/archive.html?date=${esc(x.date)}" style="text-decoration:none;color:inherit"><div><div class="past-date">${esc(x.date)}</div><div class="past-issue">${esc(label(n))}</div></div><div><b>${esc(summary(x)||"8담당 DAILY MARKET BRIEF")}</b><div class="past-summary">${isEn()?"Validated saved edition":"검증 완료 저장본"}</div></div><div class="past-open">${isEn()?"Open →":"보기 →"}</div></a>`}).join("")}</div>${more?`<div class="archive-more-wrap"><button class="archive-more" id="archive-more-btn">${isEn()?"Show 30 more":"이전 브리프 30호 더 보기"}</button></div>`:""}`;document.getElementById("archive-more-btn")?.addEventListener("click",()=>{visibleCount+=PAGE_SIZE;renderArchive()})}
  async function load(){style();filterCalendar();[archiveDates,publication]=await Promise.all([idx(),pub()]);const current=publication?.issueDateKST||null,candidates=archiveDates.filter(d=>d!==current).sort().reverse();cachedEditions=await Promise.all(candidates.map(async date=>({date,data:await ed(date)})));renderCurrent();renderArchive()}
  const old=window.setLang;if(typeof old==="function")window.setLang=function(x){old(x);filterCalendar();renderCurrent();renderArchive()};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",load,{once:true});else load();
})();
