const MODEL=process.env.GEMINI_MODEL||"gemini-3.5-flash-lite",BASE="https://generativelanguage.googleapis.com/v1beta/models",O=process.env.GITHUB_OWNER||"supermegayoon",R=process.env.GITHUB_REPO||"Newsletter-for-Div-8",B=process.env.GITHUB_BRANCH||"main",F="competitor-current.json";
const BUYERS=[{label:"Kohl's",c:[["Target",120,"MAIN"],["JCPenney",100,"MAIN"],["Macy's",98,"MAIN"],["Walmart",70,"SECONDARY"]]},{label:"A&F / Hollister",c:[["American Eagle",115,"MAIN"],["Aritzia",112,"MAIN"],["Urban Outfitters",110,"MAIN"],["Free People",108,"MAIN"],["Anthropologie",106,"MAIN"],["J.Crew",72,"SECONDARY"],["Zara",68,"SECONDARY"]]},{label:"Macy's",c:[["Nordstrom",110,"MAIN"],["JCPenney",102,"MAIN"],["Dillard's",100,"MAIN"]]},{label:"Ann Taylor",c:[["Banana Republic",110,"MAIN"],["J.Crew",105,"MAIN"],["White House Black Market",100,"MAIN"]]},{label:"Talbot's",c:[["J.Jill",110,"MAIN"],["Chico's",105,"MAIN"],["Lands' End",100,"MAIN"]]}];
const kst=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
async function gh(u,o={}){let r=await fetch(u,{...o,headers:{Authorization:`Bearer ${process.env.GITHUB_TOKEN}`,Accept:"application/vnd.github+json",...(o.headers||{})}}),t=await r.text(),j={};try{j=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(j.message||`GitHub ${r.status}`);return j}
async function read(){let j=await gh(`https://api.github.com/repos/${O}/${R}/contents/${F}?ref=${B}`);return{data:JSON.parse(Buffer.from(String(j.content||"").replace(/\n/g,""),"base64").toString()),sha:j.sha}}
async function save(x,sha){let b={message:`Competitor ${x.generatedDateKST}`,content:Buffer.from(JSON.stringify(x,null,2)+"\n").toString("base64"),branch:B};if(sha)b.sha=sha;return gh(`https://api.github.com/repos/${O}/${R}/contents/${F}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)})}
const clean=s=>String(s||"").replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim(),tag=(b,n)=>{let m=b.match(new RegExp(`<${n}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${n}>`,"i"));return m?clean(m[1]):""};
async function rss(c){let[n,w,ct]=c,r=await fetch(`https://news.google.com/rss/search?q=${encodeURIComponent(n+" apparel fashion product promotion retail store when:7d")}&hl=en-US&gl=US&ceid=US:en`,{headers:{"User-Agent":"Mozilla/5.0"}});let xml=await r.text();return[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(x=>x[1]).map(b=>({name:n,competitorTier:ct,title:tag(b,"title"),description:tag(b,"description"),date:tag(b,"pubDate"),url:(b.match(/<link>([\s\S]*?)<\/link>/i)||[])[1]||"",score:w})).slice(0,12)}
function text(j){return(j?.candidates?.[0]?.content?.parts||[]).map(p=>p.text||"").join("").replace(/^```json\s*/i,"").replace(/\s*```$/,"").trim()}
async function synth(b,raw){let p=`Apparel competitor intelligence. Buyer=${b.label}. Select 3 most meaningful last-7-day competitor signals. Kohl's: Target highest priority. A&F/Hollister MAIN: American Eagle, Aritzia, Urban Outfitters, Free People, Anthropologie; J.Crew/Zara secondary. Never invent. Korean grammar + natural English industry terms. Return JSON ONLY {"buyer":"${b.label}","competitionLevel":"LOW|MEDIUM|HIGH","keyTakeaway":{"kr":"","en":""},"competitors":[{"name":"","signal":"PRICE|PRODUCT|PROMOTION|CHANNEL|STORE|DIGITAL|SOURCING|FINANCIAL","move":{"kr":"","en":""},"whyItMatters":{"kr":"","en":""},"action":{"kr":"","en":""},"sources":[{"source":"","sourceTier":"GENERAL","date":"YYYY.MM.DD","url":""}]}]}. EVIDENCE=${JSON.stringify(raw)}`;let r=await fetch(`${BASE}/${encodeURIComponent(MODEL)}:generateContent`,{method:"POST",headers:{"x-goog-api-key":process.env.GEMINI_API_KEY,"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:p}]}],generationConfig:{temperature:.25,maxOutputTokens:4000,responseMimeType:"application/json"}})}),j=await r.json();if(!r.ok)throw Error(j?.error?.message||`Gemini ${r.status}`);return JSON.parse(text(j))}
async function build(){let buyers=[];for(let b of BUYERS){let s=await Promise.allSettled(b.c.map(rss)),raw=s.flatMap(x=>x.status==="fulfilled"?x.value:[]);buyers.push(await synth(b,raw))}return{ok:true,generatedDateKST:kst(),asOf:new Date().toISOString(),schedule:"Mon-Fri 08:00 KST",windowDays:7,buyers}}
module.exports=async(req,res)=>{res.setHeader("Cache-Control","no-store");let old=null,sha=null;try{let x=await read();old=x.data;sha=x.sha}catch{}let force=String(req.query?.force||"")==="1"&&(!process.env.CRON_SECRET||req.headers.authorization===`Bearer ${process.env.CRON_SECRET}`);if(!force&&old)return res.status(200).json(old);if(!force)return res.status(503).json({error:"No competitor snapshot yet"});try{let x=await build();await save(x,sha);return res.status(200).json(x)}catch(e){return res.status(503).json({error:e.message})}};
